[workspace]
resolver = "2"
members = ["hd2m_gui", "hd2m_search"]

[workspace.package]
version = "0.1.0"
authors = ["Preco Plusb <plusb21@gmail.com>"]
repository = "https://github.com/preco21/nxzr"
license = "UNLICENSED"
