[package]
name = "hd2m_cv"
description = "hd2m: Some computer-vision related tools"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.81"
half = "2.4.0"
ndarray = { version = "0.15.6", features = ["rayon"] }
opencv = "0.88.8"
strum = { version = "0.26.2", features = ["derive"] }
